use_frameworks!

target 'datamuse-swift_Example' do
  pod 'datamuse-swift', :path => '../'

  target 'datamuse-swift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
